### ISSUE TITLE
appcode.jar file sizes

### ISSUE THREAD

**Issue by evliu** [zchee/Seti_JetBrains#24]
is there a reason why the original jar is 119.5MB and the processed one is 54.6? I feel like that means a lot of stuff is missing. That may be why I've had issues here and there with Appcode on my recent project.

**Comment by zchee** [comment]
@evliu 
Thank you as always post of issue!
and, If this problem is cause your appcode is not working properly, I'm sorry.

I was aware of the difference in size from the previous.

When I decompile in Intellij IDEA, Maybe Jetbrains was compiled use Java 6.
but, I re-building jar use `openjdk version "1.8.0_66-internal"`.
See https://github.com/zchee/Seti_JetBrains/releases comments.

I think maybe that it's a problem.

**Comment by evliu** [comment]
I unzipped and re-jarred without making any changes and the size is also a lot smaller too so I don't think it's the problem. Issue improbably because it was EAP. Thanks!

**Comment by zchee** [comment]
@evliu OK :) Thanks.

**Comment by evliu** [comment]
@zchee I figured it out (I think), on line 19 of Dockerfile.appcode add `0` to the options so it won't zip compress. I'm guessing they did that so it would run faster possibly

```
RUN jar c0f ../appcode.jar .
```
